code --install-extension Cardinal90.multi-cursor-case-preserve
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension formulahendry.auto-rename-tag
code --install-extension johnpapa.winteriscoming
code --install-extension JP.abaqus
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension moshfeu.compare-folders
code --install-extension mquandalle.graphql
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rangav.vscode-thunder-client
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension styled-components.vscode-styled-components
code --install-extension TabNine.tabnine-vscode
code --install-extension tamasfe.even-better-toml
code --install-extension wmaurer.change-case
